### ISSUE TITLE
Monitor above notch breaks most effects

### ISSUE THREAD

**Issue by dimitribouniol** [chockenberry/Notchmeister#1]
Original reported here: https://twitter.com/dimitribouniol/status/1471913342621028353

If you have a monitor arranged above the screen with a notch, many effects will break if you drag your cursor up through the notch and onto the external display. For instance, Nano Radar will continue showing the radar. If you then switch the effect, the old one will be stuck on screen.

Additionally, for Cylon, having an external display will zap the mouse pointer to the external display.

A final issue is on first launch, a dummy notch was placed on my central external display, but I haven't been able to reproduce it since.

My monitor layout. Note that the menubar is configured on the external display, and not the display with the notch:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/225505/146596785-907ace55-6746-4d75-8174-0a9eaabb60c9.png">

**Comment by chockenberry** [comment]
I _think_ this was fixed with the @danielpunkass fix for detecting screen configuration changes. Since I don't have your external monitors, nor a new MacBook, I'd like you to confirm the fix for this issue.

Here's a public TestFlight: https://testflight.apple.com/join/pIGViV74

**Comment by dimitribouniol** [comment]
Unfortunately still happens, but not with all effects. The festive lights now disappear when the mouse goes up, but I can confirm Cylon, plasma leak and radar all get stuck if the mouse moves upwards to the external display through the notch. (I'm not sure if glow also got stuck, but I don't think it did)

Here is a screenshot of those effects running simultaneously (festive being the current one).

<img width="246" alt="image" src="https://user-images.githubusercontent.com/225505/147516321-a37403e5-de7b-479f-bf90-4bbd3118b5fb.png">

**Comment by chockenberry** [comment]
@dimitribouniol I'm clearly making some bad assumptions here - and testing those assumptions. Can you run this playground and put the `print` results here?

http://files.iconfactory.net/software/beta/NotchTest.playground.zip

Those numbers should allow me to test this configuration more accurately. Also, are you running on a 14" or 16" MacBook Pro?

**Comment by dimitribouniol** [comment]
This is a 16" MacBook Pro. Here are the results:

```
0: frame = (0.0, 0.0, 3008.0, 1692.0), visibleFrame = (0.0, 73.0, 3008.0, 1594.0), notchRect = nil, main = true
1: frame = (670.0, -1117.0, 1728.0, 1117.0), visibleFrame = (670.0, -1117.0, 1728.0, 1079.0), notchRect = Optional((1441.0, -32.0, 185.0, 32.0)), main = false
2: frame = (3008.0, -868.0, 1440.0, 2560.0), visibleFrame = (3008.0, -868.0, 1440.0, 2535.0), notchRect = nil, main = false
3: frame = (-1440.0, -868.0, 1440.0, 2560.0), visibleFrame = (-1440.0, -868.0, 1440.0, 2535.0), notchRect = nil, main = false
```

Feel free to let me know what branch/PR you are testing on, I can always run it locally in Xcode and report back if it works or not.

**Comment by danielpunkass** [comment]
Probably the same root cause as #5

**Comment by chockenberry** [comment]
This issue should be fixed in the latest TestFlight build: https://testflight.apple.com/join/pIGViV74

**Comment by dimitribouniol** [comment]
Can verify that it works great!
